---
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: argo-workflows-role-pdep
spec:
  providerConfigRef:
    name: keycloak
  forProvider:
    realmId: platform
    clientIdRef:
      name: argo-workflows
    name: pdep
    description: Argo Workflows pdep profe role
    compositeRolesRefs:
      - name: argo-workflows-restricted-access
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdep-user
  annotations:
    workflows.argoproj.io/rbac-rule: "'pdep' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "100"
---
apiVersion: v1
kind: Secret
metadata:
  name: pdep-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: pdep-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pdep-role
rules:
  # from https://argo-workflows.readthedocs.io/en/latest/security/#ui-access
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  # Argo APIs. See also https://github.com/argoproj/argo-workflows/blob/main/manifests/cluster-install/workflow-controller-rbac/workflow-aggregate-roles.yaml#L4
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pdep-role-user-binding
subjects:
  - kind: ServiceAccount
    name: pdep-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pdep-role
